### ISSUE TITLE
anki-vim command not found

### ISSUE THREAD

**Issue by jamiewright814** [MFreidank/AnkiVim#13]
I have Python 3.9 installed on macOS. I've successfully installed the AnkiVim package version 1.5.3 according to the 'pip3 list' command. Its path is /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages on my computer.

However, if I run 'anki-vim -h' or 'anki-vim DECKNAME' etc on the command line, 'command not found: anki-vim' is returned. I've tried lots of different commands and fiddled around but nothing seems to be working. I was wondering if i am missing something obvious or this is an issue. Thanks in advance.

**Comment by MFreidank** [comment]
Hi @akj0991 

Could you please see if you can find an "anki-vim" script under the following path:
`/Library/Frameworks/Python.framework/Versions/3.9/bin/anki-vim`

If yes, could you try to execute that script directly, e.g. by issuing:
`/Library/Frameworks/Python.framework/Versions/3.9/bin/anki-vim -h`

Please report back if that works.

Many thanks in advance and kind regards,
MFreidank

**Comment by MFreidank** [comment]
Hi @akj0991 - did you get a chance to try the above out?

Kind regards,
MFreidank

**Comment by MFreidank** [comment]
Closed as it has been stale for > 1 month.
Will reopen in case the issue sees activity in the future.
