### ISSUE TITLE
Please add this on vimawesome

### ISSUE THREAD

**Issue by Zumh** [MFreidank/AnkiVim#14]
It will be awesome. I fyou could add this on vimawesome.com
Thank so much for making this work.

**Comment by MFreidank** [comment]
It seems that this homepage mainly tracks vim plugins. 
`AnkiVim` is not a plugin, but rather an external tool leveraging vim for heavy lifting. 

Most importantly: there's no way to make it installable using `Vim` package managers. 

Therefore, as much as I appreciate the work of the team over at vimawesome, I don't believe it belongs there.
