### ISSUE TITLE
Cannot run anki-vim on Windows

### ISSUE THREAD

**Issue by pinaki2** [MFreidank/AnkiVim#15]
I'm on Windows 10. I installed AnkiVim but cannot run the command anki-vim. I think the script anki-vim.py didn't get installed. Are you aware of any such issue on Windows? Thanks.

> C:\Users\pinaki>pip install AnkiVim
> Collecting AnkiVim
>   Downloading AnkiVim-1.5.3-py3-none-any.whl (7.8 kB)
> Installing collected packages: AnkiVim
> Successfully installed AnkiVim-1.5.3
> 
> C:\Users\pinaki>anki-vim -h
> 'anki-vim' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Users\pinaki>pip freeze | findstr AnkiVim
> AnkiVim==1.5.3
> 
> C:\Users\pinaki>pip show AnkiVim
> Name: AnkiVim
> Version: 1.5.3
> Summary: Use vim to rapidly write textfiles immediately importable into anki(1).
> Home-page: https://github.com/MFreidank/VimForAnki
> Author: Moritz Freidank
> Author-email: freidankm@yahoo.de
> License: MIT
> Location: C:\Users\pinaki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
> Requires:
> Required-by:
> 
>

**Comment by MFreidank** [comment]
@pinaki2 Can you please try to give a full path to it, like so:
`/path/to/python C:\Users\pinaki\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311/site-packages/bin/anki-vim.py`

Let me know if it worked.

**Comment by MFreidank** [comment]
Closing as this issue is stale.
