### ISSUE TITLE
Doesn't work: ValueError

### ISSUE THREAD

**Issue by qazip** [MFreidank/AnkiVim#5]
```
anki-vim -e nvim statistics
Traceback (most recent call last):
  File "/home/user/.local/bin/anki-vim", line 90, in <module>
    main()
  File "/home/user/.local/bin/anki-vim", line 55, in main
    raise ValueError()
ValueError
```

I have python 3.7.2.

**Comment by MFreidank** [comment]
Hi, the following should work:
`anki-vim -e nvim --editor-args="" statistics`
... or using `nano` per your other issue instead. 

This is (somewhat) documented if you run:
`anki-vim -h`

But thanks a lot for opening the issue, I don't like how I am handling different editor choices at the moment. I will push a fix that will allow you to simply run your stated command in the next days and report when it is there. Until then, I hope my workaround above will be helpful.
