### ISSUE TITLE
Update existing decks

### ISSUE THREAD

**Issue by AdrienLemaire** [MFreidank/AnkiVim#8]
Hi @MFreidank , thanks for making this tool.

I'd like to update an existing deck I've been studying for a few months now, and that's basically duplicating all cards, editing the questions with prefixes "reading:" and "meaning:" beforehand, and have the already studied cards being edited as "reading:".

I only read your README, but it looks like your tool allows creating decks from vim, not really updating existing ones (I do not want to lose the review history on all already-learnt cards).
Do you have a suggestion on how to do so ?

**Comment by MFreidank** [comment]
Hi @AdrienLemaire, you are right, with one nitpick: it is possible to import new cards created with `AnkiVim` into an existing deck. However, currently we have no means to update existing cards programmatically while retaining their review history. 

However, go check out:
https://github.com/FooSoft/anki-connect

That project accomodates your use case well (it was created around the same time as mine and has a nice versatile angle - I have a loose plan to integrate with them some time in the future).
